export default [
  {   id:"1",
      name:'Faculty of Engineering and Information Technology',
      course1:'Engineering',
      course2:'Mathematics',
      course3:'Computer Science',
      course4:'Statistics',
      
  },
  {   id:"2",
      name:'Faculty of Engineering and Information Technology',
      course1:'Engineering',
      course2:'Mathematics',
      course3:'Computer Science',
      course4:'Statistics',
      
  },
  {   id:"3",
      name:'Faculty of Engineering and Information Technology',
      course1:'Engineering',
      course2:'Mathematics',
      course3:'Computer Science',
      course4:'Statistics',
      
  },
  {   id:"4",
      name:'Faculty of Engineering and Information Technology',
      course1:'Engineering',
      course2:'Mathematics',
      course3:'Computer Science',
      course4:'Statistics',
      
  },
  {   id:"5",
      name:'Faculty of Engineering and Information Technology',
      course1:'Engineering',
      course2:'Mathematics',
      course3:'Computer Science',
      course4:'Statistics',
      
  },
  {   id:"6",
      name:'Faculty of Engineering and Information Technology',
      course1:'Engineering',
      course2:'Mathematics',
      course3:'Computer Science',
      course4:'Statistics',
      
  },
]